/*
SQLyog Community v9.20 
MySQL - 5.1.49-1ubuntu8.1 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `creature_template` (
	`entry` mediumint (8),
	`difficulty_entry_1` mediumint (8),
	`difficulty_entry_2` mediumint (8),
	`difficulty_entry_3` mediumint (8),
	`KillCredit1` int (11),
	`KillCredit2` int (11),
	`modelid1` mediumint (8),
	`modelid2` mediumint (8),
	`modelid3` mediumint (8),
	`modelid4` mediumint (8),
	`name` char (300),
	`subname` char (300),
	`IconName` char (300),
	`gossip_menu_id` mediumint (8),
	`minlevel` tinyint (3),
	`maxlevel` tinyint (3),
	`exp` smallint (2),
	`faction_A` smallint (5),
	`faction_H` smallint (5),
	`npcflag` int (10),
	`speed_walk` float ,
	`speed_run` float ,
	`scale` float ,
	`rank` tinyint (3),
	`mindmg` float ,
	`maxdmg` float ,
	`dmgschool` tinyint (4),
	`attackpower` int (10),
	`dmg_multiplier` float ,
	`baseattacktime` int (10),
	`rangeattacktime` int (10),
	`unit_class` tinyint (3),
	`unit_flags` int (10),
	`dynamicflags` int (10),
	`family` tinyint (4),
	`trainer_type` tinyint (4),
	`trainer_spell` mediumint (8),
	`trainer_class` tinyint (3),
	`trainer_race` tinyint (3),
	`minrangedmg` float ,
	`maxrangedmg` float ,
	`rangedattackpower` smallint (5),
	`type` tinyint (3),
	`type_flags` int (10),
	`lootid` mediumint (8),
	`pickpocketloot` mediumint (8),
	`skinloot` mediumint (8),
	`resistance1` smallint (5),
	`resistance2` smallint (5),
	`resistance3` smallint (5),
	`resistance4` smallint (5),
	`resistance5` smallint (5),
	`resistance6` smallint (5),
	`spell1` mediumint (8),
	`spell2` mediumint (8),
	`spell3` mediumint (8),
	`spell4` mediumint (8),
	`spell5` mediumint (8),
	`spell6` mediumint (8),
	`spell7` mediumint (8),
	`spell8` mediumint (8),
	`PetSpellDataId` mediumint (8),
	`VehicleId` mediumint (8),
	`mingold` mediumint (8),
	`maxgold` mediumint (8),
	`AIName` char (192),
	`MovementType` tinyint (3),
	`InhabitType` tinyint (3),
	`Health_mod` float ,
	`Mana_mod` float ,
	`Armor_mod` float ,
	`RacialLeader` tinyint (3),
	`questItem1` int (11),
	`questItem2` int (11),
	`questItem3` int (11),
	`questItem4` int (11),
	`questItem5` int (11),
	`questItem6` int (11),
	`movementId` int (11),
	`RegenHealth` tinyint (3),
	`equipment_id` mediumint (8),
	`mechanic_immune_mask` int (10),
	`flags_extra` int (10),
	`ScriptName` char (192),
	`WDBVerified` smallint (5)
); 
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('36940','37550','0','0','0','0','24993','0','0','0','Raging Ghoul','','','0','80','80','2','2123','2123','0','2','1.42857','1','0','422','586','0','642','1','2000','0','1','0','8','0','0','0','0','0','345','509','103','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','1','1','1','0','0','0','0','0','0','0','151','1','0','8388624','0','npc_raging_gnoul','12340');
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('36941','37551','0','0','0','0','25245','0','0','0','Risen Witch Doctor','','','0','80','80','2','1771','1771','0','2','1.42857','1','1','417','582','0','608','7.5','2000','0','2','0','8','0','0','0','0','0','341','506','80','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','6','1','1','0','0','0','0','0','0','0','151','1','0','8388624','0','npc_risen_witch_doctor','12340');
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('37069','37549','0','0','0','0','30503','0','0','0','Lumbering Abomination','','','0','80','80','2','1771','1771','0','1','1.14286','1','1','422','586','0','642','7.5','2000','0','1','0','8','0','0','0','0','0','345','509','103','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','10','1','1','0','0','0','0','0','0','0','0','1','0','8388624','0','npc_abon','12340');
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('37549','0','0','0','0','0','30503','0','0','0','Lumbering Abomination (1)','','','0','80','80','2','1771','1771','0','1','1.14286','1','1','422','586','0','642','13','0','0','1','0','8','0','0','0','0','0','345','509','103','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','15','1','1','0','0','0','0','0','0','0','0','1','0','8388624','0','','12340');
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('37550','0','0','0','0','0','24993','0','0','0','Raging Ghoul (1)','','','0','80','80','2','1771','1771','0','1','1.14286','1','0','422','586','0','642','1','0','0','1','0','8','0','0','0','0','0','345','509','103','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','1.5','1','1','0','0','0','0','0','0','0','151','1','0','8388624','0','','12340');
insert into `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) values('37551','0','0','0','0','0','25245','0','0','0','Risen Witch Doctor (1)','','','0','80','80','2','1771','1771','0','1','1.14286','1','1','417','582','0','608','13','0','0','2','0','8','0','0','0','0','0','341','506','80','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','0','3','7.5','1','1','0','0','0','0','0','0','0','151','1','0','8388624','0','','12340');
